### ISSUE TITLE
Some suggested changes

### ISSUE THREAD

**Issue by baandab** [volterra4/synologyshareautomount#1]
Hi - four suggested changes.

If the IP address you are checking has a redirect, the script fails.  A redirect might happen if your IP is "http://" and the website redirects to "https://"

Change this 
` cryptpass=$(curl -s $1?$2)`

to

`cryptpass=$(curl -Ls --max-redirs 2 $1?$2)`

Add the full path for synoshare (in case the PATH is not setup correctly):
`result=$(/usr/syno/sbin/synoshare --enc_mount $2 $password)`

Move the sleep to the bottom of the while loop:

from 
```
    while [[ $count -ne 0 ]] ; do
        sleep $delay

```
to
```
                ((count = count - 1))
                sleep $delay
done

```

And then, to quickly end when the mount works, add "delay=0" after this:
```
echo "["$(date)"] - Mount successful! "
delay=0
```

**Comment by volterra4** [comment]
Hello!

Thanks a lot for the suggested modifications and fixes :smiley: I've implemented them and pushed a new version of the code.
